export default {
  font: {
    light: 'RobotoCondensed-Light',
    regular: 'RobotoCondensed-Regular',
    bold: 'RobotoCondensed-Bold',
    size: {
      nano: '10px',
      xnano: '12px',
      xxnano: '14px',
      small: '16px',
      xsmall: '18px',
      medium: '20px',
      large: '24px',
      xlarge: '32px',
      xxlarge: '40px',
      huge: '48px',
    },
  },
  colors: {
    primary: '#000000',
    secondary: '#FFFFFF',
    tertiary: '#f78e1f',
    white: '#FFFFFF',
    dark: '#000000',
    darklight: '#1f222a',
    input: '#EBEBEB',
    grayMedium: 'rgba(255, 255, 255, 0.15);',
    success: '#2CB34A',
    error: '#ED1B24',
    transparent: 'transparent',
    shadown: '#00000040',
  },
  spacings: {
    nano: '4px',
    xnano: '8px',
    xxnano: '12px',
    small: '16px',
    xsmall: '20px',
    medium: '24px',
    large: '28px',
    xlarge: '32px',
    xxlarge: '36px',
    huge: '40px',
  },
} as const;
